### ISSUE TITLE
weblogsubmit.py is running, but no submissions ?

### ISSUE THREAD

**Issue by ktrue** [DShield-ISC/dshield#58]
I've manually moved in julrich's fix to weblogsubmit.py to /srv/dshield/weblogsubmit.py.

Cron shows it running every 30 minutes 
```
Jul 23 18:03:01 TRP2HP CRON[12912]: (root) CMD (cd /srv/dshield; ./weblogsubmit.py)
Jul 23 18:33:01 TRP2HP CRON[23743]: (root) CMD (cd /srv/dshield; ./weblogsubmit.py)
Jul 23 19:03:01 TRP2HP CRON[470]: (root) CMD (cd /srv/dshield; ./weblogsubmit.py)
Jul 23 19:33:01 TRP2HP CRON[9297]: (root) CMD (cd /srv/dshield; ./weblogsubmit.py)
Jul 23 20:03:01 TRP2HP CRON[18605]: (root) CMD (cd /srv/dshield; ./weblogsubmit.py)
```
but nothing shows on Dshield or via status
```
Last Web Log Received:
Last 404 Log Received:
Last ssh Log Received: 2017-07-23 19:45:26
Last ssh Firewall Log Received: 2017-07-23 20:05:11
Current Time/Date: 2017-07-23 20:09:03
```
Is there something else I should check (basic build is with #54 installed.

**Comment by gebhard73** [comment]
same problem here

**Comment by jullrich** [comment]
possible server side fix applied. Need to wait for more reports to see if it works. Please let me know if you see any change.

**Comment by ktrue** [comment]
Just checked my system ```
Last Web Log Received:
Last 404 Log Received: 2017-07-26 01:45:03
Last ssh Log Received: 2017-07-26 01:45:22
Last ssh Firewall Log Received: 2017-07-26 01:35:07
Current Time/Date: 2017-07-26 02:02:01
```
So the 404 log appears to be flowing.  Thanks jullrich!

**Comment by gebhard73** [comment]
thanks @jullrich , the submission is also shown for me in the dashboard
but on the details page I can't see any entry...

**Comment by jullrich** [comment]
@ktrue : not 100% sure yet with your account, but I just fixed a bug with the detail display. let me know if you are seeing logs now.

**Comment by ktrue** [comment]
@jullrich it still shows submissions, but no detail data on the 404 page.
```
Last Web Log Received:
Last 404 Log Received: 2017-07-26 14:15:03
Last ssh Log Received: 2017-07-26 13:45:21
Last ssh Firewall Log Received: 2017-07-26 14:05:11
Current Time/Date: 2017-07-26 14:15:50
```

**Comment by gebhard73** [comment]
same for me ...

**Comment by jullrich** [comment]
ok. found another bug. Let me know if you see the reports by the end of today.
keeping this open until I have confirmation that it works.

**Comment by gebhard73** [comment]
first report just has shown up, thanks @jullrich 
if @ktrue also sees reports coming in we may close this issue IMHO

**Comment by ktrue** [comment]
My first report has also shown up on the 404 Reports page.  Thanks @jullrich !

I think we can close this issue :)
